all: prob1_write prob1_read prob1_readsystemcalls

prob1_write: prob1_write.c
	gcc -Wall -o prob1_write prob1_write.c

prob1_read: prob1_read.c
	gcc -Wall -o prob1_read prob1_read.c

prob1_readsystemcalls: prob1_readsystemcalls.c
	gcc -Wall -o prob1_readsystemcalls prob1_readsystemcalls.c